In [1]:
import ipywidgets as widgets
from IPython.display import display
import pandas as pd
import plotly.express as px

In [2]:
# load data from previous notebooks
aadt_df = pd.read_csv('intermediate/external-historic-aadt.csv')
linear_forecast_df = pd.read_csv('results/linear-forecasts.csv')
externals_df = pd.read_csv('params/externals.csv')
previous_forecasts_df = pd.read_csv('intermediate/previous-forecasts.csv')
external_xy_df = pd.read_csv('data/external-x-y.csv')

Create interactive chart with assist from ChatGPT: https://chat.openai.com/share/496c1584-22b6-4c72-9815-395e11718907

In [3]:
previous_forecasts_df

     externalid  year     AADT forecast
0          3601  2020    750.0     v900
1          3602  2020   9570.0     v900
2          3603  2020   1480.0     v900
3          3604  2020  28390.0     v900
4          3605  2020   3840.0     v900
..          ...   ...      ...      ...
140        3625  2060    200.0     v900
141        3626  2060   5250.0     v900
142        3627  2060    450.0     v900
143        3628  2060  54260.0     v900
144        3629  2060   3660.0     v900

[145 rows x 4 columns]

In [4]:
# MAKE INTERACTIVE CHART

# Create a lookup dictionary
name_lookup = externals_df.set_index('externalid')['name'].to_dict()

# Map names to the forecast df
linear_forecast_df['name'] = linear_forecast_df['externalid'].map(name_lookup)

# Build the final string
linear_forecast_df['external'] = (
    'Ext # ' +
    linear_forecast_df['externalid'].fillna(0).astype(int).astype(str) +
    ' - ' +
    linear_forecast_df['name'].fillna('')
)

# Map names to the forecast df
previous_forecasts_df['name'] = previous_forecasts_df['externalid'].map(name_lookup)

# Build the final string
previous_forecasts_df['external'] = (
    'Ext # ' +
    previous_forecasts_df['externalid'].fillna(0).astype(int).astype(str) +
    ' - ' +
    previous_forecasts_df['name'].fillna('')
)
previous_forecasts_df = previous_forecasts_df[previous_forecasts_df['year'] > 2023]

# Map names to the forecast df
aadt_df['name'] = aadt_df['externalid'].map(name_lookup)

# Build the final string
aadt_df['external'] = (
    'Ext # ' +
    aadt_df['externalid'].fillna(0).astype(int).astype(str) +
    ' - ' +
    aadt_df['name'].fillna('')
)

# Create a dropdown widget for external selection
external_widget = widgets.Dropdown(
    options=previous_forecasts_df['external'].unique().tolist(),
    description='external:',
    disabled=False
)

projgrp_widget = widgets.SelectMultiple(
    options=sorted(linear_forecast_df['PROJ_GRP'].dropna().unique()),
    description='Proj Groups:',
    disabled=False
)

# Display function
def plot_data(external, projgrp):

    output.clear_output()
    global firstTime
   
    if firstTime:
        firstTime = False
    else:
        filteredlinear_forecast_df = linear_forecast_df[(linear_forecast_df['external'] == external) & (linear_forecast_df['PROJ_GRP'].isin(projgrp))]
        filteredaadt_df = aadt_df[(aadt_df['external'] == external)]
        filteredprevious_forecast_df = previous_forecasts_df[(previous_forecasts_df['external'] == external)]
        fig = px.line(filteredlinear_forecast_df, x='year', y='linear_forecast', color='PROJ_GRP',
                    title=f'Linear Forecast for {external}',
                    labels={'linear_forecast': 'AADT', 'year': 'Year'},
                    markers=True) 
        fig.update_traces(line=dict(dash='dash'))
        fig.update_traces(marker=dict(size=20))
    
        # Adding the scatter plot from dfHistoricAADT
        fig.add_scatter(x=filteredaadt_df['year'], y=filteredaadt_df['AADT'], mode='markers', 
                        marker=dict(size=10, color='darkgrey', symbol='circle'), name='Historic AADT')
        
        fig.update_layout(height=500, width=1000)
        fig.update_xaxes(range=[1980, 2060+2])

        max_LinF = linear_forecast_df[(linear_forecast_df['external'] == external)]['linear_forecast'].max()
        max_Aadt = filteredaadt_df['AADT'].max()
        overall_max = max(max_LinF, max_Aadt)
        fig.update_yaxes(range=[0,overall_max+1000])
    
        # Adding the scatter plot from dfHistoricAADT
        fig.add_scatter(x=filteredprevious_forecast_df['year'], y=filteredprevious_forecast_df['AADT'], mode='markers', 
                        marker=dict(size=10, color='orange', symbol='circle'), name='v9.0 Forecast')
                                    
        fig.show()
        
# to keep VS CODE from duplicating chart images use global firstTime
firstTime = True

# create output widget to display filtered DataFrame
output = widgets.Output()
vbox = widgets.VBox([external_widget, projgrp_widget])

# create interactive widget
interactive_output = widgets.interactive_output(plot_data, {'external': external_widget, 'projgrp': projgrp_widget})
hbox2 = widgets.HBox([vbox, interactive_output])

# Display a markdown heading
display(hbox2)
#display(interactive_output)
display(output)

HBox(children=(VBox(children=(Dropdown(description='external:', options=('Ext # 3601 - FAR-1082 Bird Refuge', …

Output()

In [5]:
selected_forecast_df = pd.DataFrame([
    [3601, 'Since 2003', 'as early as there is data'                                                                                    ],
    [3602, 'Since 1981', 'as early as there is data, and trying not to get too high when using 2002 or higher'                          ],
    [3603, 'Since 2016', 'trying to split difference between forecast using earlier data and forecast using 2020+ data'                 ],
    [3604, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3605, 'Since 2002', 'earlier data jumps areound too much'                                                                          ],
    [3606, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3607, 'Since 2007', 'data does not look consistent till 2007'                                                                      ],
    [3608, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3609, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3610, 'No Data'   , ''                                                                                                             ],
    [3611, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3612, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3613, 'Since 2009', 'pre 2009 data is much higher than post 2009 data'                                                             ],
    [3614, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3615, 'Since 2007', 'erratic data. 2007 tries to split difference between 2004-2012 data and 2013-2023 data'                       ],
    [3616, 'Since 2006', 'data pretty consistent since 2006'                                                                            ],
    [3617, 'Since 2011', 'data pretty consistent since 2011'                                                                            ],
    [3618, 'Since 2007', 'data pretty consistent since 2007, but forecast from 1981 is much higher than 2007-2023 data'                 ],
    [3619, 'No Data'   , ''                                                                                                             ],
    [3620, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3621, 'No Data'   , ''                                                                                                             ],
    [3622, 'No Data'   , ''                                                                                                             ],
    [3623, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time. outlier in 1983 does not change the trend'],
    [3624, 'Since 1990', 'data pretty consistent since 2017, but puts forecast too high'                                                ],
    [3625, 'No Data'   , ''                                                                                                             ],
    [3626, 'Since 1981', 'as early as there is data, despite some variation early on, trend looks pretty consistent over time'          ],
    [3627, 'No Data'   , ''                                                                                                             ],
    [3628, 'Since 1984', 'as early as there is data, trend looks pretty consistent over time except for past two years, keep eye on it' ],
    [3629, 'Since 2011', 'data pretty consistent since 2011'                                                                            ]
], columns=['externalid','PROJ_GRP', 'linear_forecast_notes'])

linear_forecast_selected_df = pd.merge(selected_forecast_df, linear_forecast_df, on=['externalid','PROJ_GRP'])
linear_forecast_selected_df

,externalid,PROJ_GRP,linear_forecast_notes,segid,year,linear_forecast,name,external
0,3601,Since 2003,as early as there is data,1082_000.0,2003,412,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
1,3601,Since 2003,as early as there is data,1082_000.0,2027,890,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
2,3601,Since 2003,as early as there is data,1082_000.0,2032,989,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
3,3601,Since 2003,as early as there is data,1082_000.0,2036,1069,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
4,3601,Since 2003,as early as there is data,1082_000.0,2046,1268,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
...,...,...,...,...,...,...,...,...
198,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2032,4248,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
199,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2036,4588,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
200,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2046,5437,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
201,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2055,6202,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
202,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2060,6627,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms

In [6]:
def preprocess_final_forecast_df(external, manual_adj_df):
    # Filter necessary datasets
    filtered_forecast = linear_forecast_selected_df[linear_forecast_selected_df['external'] == external]
    filtered_manual = manual_adj_df[manual_adj_df['external'] == external]

    # Merge manual adjustments
    merged = pd.merge(
        filtered_forecast,
        filtered_manual,
        on=['externalid', 'year'],
        how='left'
    )
    merged = merged[merged['year'] >= 2023]

    # Calculate 'final_forecast'
    merged['final_forecast'] = merged.apply(
        lambda row: row['linear_forecast'] + row['manual_adj'] if pd.notnull(row['manual_adj']) else row['linear_forecast'],
        axis=1
    )

    # Apply rounding
    def custom_round(x):
        if x < 100:
            return round(x / 10) * 10
        elif x < 1000:
            return round(x / 50) * 50
        elif x < 10000:
            return round(x / 100) * 100
        elif x < 100000:
            return round(x / 500) * 500
        else:
            return round(x / 1000) * 1000

    merged['final_forecast'] = merged['final_forecast'].apply(custom_round)

    return merged

In [7]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import ipywidgets as widgets
import folium
from folium import Map, Marker
from IPython.display import display, clear_output
import pyproj  # 🧭 to convert UTM to Lat/Lon
from io import BytesIO
import base64
import numpy as np

# === Dropdown Widget
external_widget = widgets.Dropdown(
    options=previous_forecasts_df['external'].unique().tolist(),
    description='external:',
    disabled=False
)

output = widgets.Output()
firstTime = True

# === Helper function: Convert UTM to Latitude/Longitude
def utm12n_to_latlon(x, y):
    transformer = pyproj.Transformer.from_crs("EPSG:32612", "EPSG:4326", always_xy=True)
    lon, lat = transformer.transform(x, y)
    return lat, lon

# === Main Plot Function
def plot_data(external, final_forecast_df):
    output.clear_output()
    global firstTime

    if firstTime:
        firstTime = False
    else:
        with output:
            # === Filter datasets
            filteredlinear_forecast_selected_df = linear_forecast_selected_df[(linear_forecast_selected_df['external'] == external)]
            filteredaadt_df = aadt_df[(aadt_df['external'] == external)]
            filteredprevious_forecast_df = previous_forecasts_df[(previous_forecasts_df['external'] == external)]
            
            filtered_final_forecast_df = final_forecast_df[final_forecast_df['external'] == external]

            # === Create Plotly Figure
            fig = px.line(
                filteredlinear_forecast_selected_df,
                x='year',
                y='linear_forecast',
                title=f'Forecast for {external}',
                labels={'linear_forecast': 'AADT', 'year': 'Year'},
            )
            fig.update_traces(line=dict(color='lightblue'), mode='lines+markers')
            fig.update_traces(marker=dict(size=20, color='lightblue', symbol='circle'))
            fig.update_traces(name="Linear Extrapolation", showlegend=True)

            # Add Historic AADT
            historic_trace = go.Scatter(
                x=filteredaadt_df['year'],
                y=filteredaadt_df['AADT'],
                mode='markers',
                marker=dict(size=10, color='darkgrey', symbol='circle'),
                name='Historic AADT'
            )
            fig.add_trace(historic_trace)
            fig.data = (fig.data[-1],) + fig.data[:-1]  # Move historic to front

            # Add other forecasts
            fig.add_scatter(
                x=filtered_final_forecast_df['year'], y=filtered_final_forecast_df['final_forecast'], mode='markers',
                marker=dict(size=15, color='red'), name='RTP 2027 Forecast'
            )

            # Extract data
            x = filtered_final_forecast_df['year']
            y = filtered_final_forecast_df['final_forecast']

            # Fit a linear regression line
            coeffs = np.polyfit(x, y, deg=1)  # Linear fit (degree 1)
            fitted_line = np.poly1d(coeffs)

            # Generate fitted y-values
            y_fit = fitted_line(x)

            # Add fitted line
            fig.add_scatter(
                x=x, y=y_fit, mode='lines',
                line=dict(color='red', dash='dash'),  # Optional: dashed line for contrast
                name='RTP 2027 Forecast Linear Fit'
            )

            fig.add_scatter(
                x=filteredprevious_forecast_df['year'], y=filteredprevious_forecast_df['AADT'], mode='markers',
                marker=dict(size=10, color='orange', symbol='circle'), name='RTP 2023 Forecast'
            )

            fig.update_yaxes(range=[0, None])
            fig.update_xaxes(range=[1980, 2062])
            fig.update_layout(height=500)

            fig.show()

#            # === Create Folium Map
#            # Find matching externalid
#            # === Lookup externalid from name
#            externalid_row = linear_forecast_selected_df[linear_forecast_selected_df['external'] == external]
#
#            if externalid_row.empty:
#                print(f"⚠️ No externalid found for external: {external}")
#                display(fig)
#                return
#
#            externalid = externalid_row['externalid'].iloc[0]
#
#            # === Try to match externalid in external_xy_df
#            matching_rows = external_xy_df[external_xy_df['externalid'] == externalid]
#
#            fig_widget = go.FigureWidget(fig)
#
#            if not matching_rows.empty:
#                matching_row = matching_rows.iloc[0]
#                x_utm = matching_row['x_utm12n']
#                y_utm = matching_row['y_utm12n']
#                lat, lon = utm12n_to_latlon(x_utm, y_utm)
#
#                fmap = folium.Map(location=[lat, lon], zoom_start=10, width=300, height=300)
#                folium.Marker([lat, lon], popup=f"{external}", tooltip="Location").add_to(fmap)
#
#                display(fmap)
#                fig_widget.show()
#            else:
#                print(f"⚠️ No location found in external_xy_df for externalid: {externalid}")
#                fig_widget.show()

In [8]:
# to keep VS CODE from duplicating chart images use global firstTime
firstTime = True

from ipywidgets import interactive_output, fixed

# create output widget to display filtered DataFrame
output = widgets.Output()
hbox = widgets.HBox([external_widget])


# Example manual adjustment data
manual_adj_df = pd.DataFrame([
    [3602, 2027,   500],
    [3602, 2032,   300],
    [3602, 2036,   200],
    [3602, 2046,   100],
    [3605, 2027,   100],
    [3608, 2027,   100],
    [3610, 2027,   100],
    [3610, 2027,   100],
    [3610, 2027,   100],
    [3612, 2027,  4000],
    [3612, 2032,  2000],
    [3612, 2036,  1000],
    [3613, 2027,    50],
    [3613, 2032,     0],
    [3613, 2036,     0],
    [3613, 2046,     0],
    [3613, 2055,     0],
    [3615, 2027, -2050], # adjust down to prior forecast
    [3615, 2032, -2200],
    [3615, 2036, -2300],
    [3615, 2046, -2600],
    [3615, 2055, -2800],
    [3615, 2060, -2900],
    [3620, 2027,   500],
    [3623, 2027,   500],
    [3623, 2032,   500],
    [3623, 2036,   500],
    [3626, 2027,   300],
    [3626, 2032,   200],
    [3626, 2036,   100],
    [3610, 2027,   100],
    [3610, 2032,   100],
    [3610, 2036,   100],
    [3610, 2046,   150],
    [3610, 2055,   150],
    [3610, 2060,   200],
    [3619, 2027,   450],
    [3619, 2032,   450],
    [3619, 2036,   500],
    [3619, 2046,   550],
    [3619, 2055,   550],
    [3619, 2060,   600],
    [3621, 2027,   350],
    [3621, 2032,   350],
    [3621, 2036,   400],
    [3621, 2046,   400],
    [3621, 2055,   450],
    [3621, 2060,   450],
    [3622, 2027,   150],
    [3622, 2032,   150],
    [3622, 2036,   150],
    [3622, 2046,   200],
    [3622, 2055,   200],
    [3622, 2060,   200],
    [3624, 2027,   600],
    [3624, 2032,   400],
    [3624, 2036,   400],
    [3624, 2046,   300],
    [3624, 2055,   100],
    [3624, 2060,     0],
    [3625, 2027,   150],
    [3625, 2032,   150],
    [3625, 2036,   150],
    [3625, 2046,   200],
    [3625, 2055,   200],
    [3625, 2060,   200],
    [3627, 2027,   350],
    [3627, 2032,   350],
    [3627, 2036,   400],
    [3627, 2046,   400],
    [3627, 2055,   450],
    [3627, 2060,   450]
], columns=['externalid','year','manual_adj'])


# Filter only needed years
forecast_df = linear_forecast_selected_df[linear_forecast_selected_df['year'] >= 2023]

# Merge manual adjustments
final_forecast_df = pd.merge(
    forecast_df,
    manual_adj_df,
    on=['externalid', 'year'],
    how='left'
)

# Compute final_forecast using manual adjustments where available
final_forecast_df['final_forecast'] = final_forecast_df.apply(
    lambda row: row['linear_forecast'] + row['manual_adj'] if pd.notnull(row['manual_adj']) else row['linear_forecast'],
    axis=1
)

# Apply custom rounding
def custom_round(x):
    if x < 100:
        return round(x / 10) * 10
    elif x < 1000:
        return round(x / 50) * 50
    elif x < 10000:
        return round(x / 100) * 100
    elif x < 100000:
        return round(x / 500) * 500
    else:
        return round(x / 1000) * 1000

final_forecast_df['final_forecast'] = final_forecast_df['final_forecast'].apply(custom_round)


# Use `fixed()` for final_forecast_df
interactive_output = widgets.interactive_output(
    plot_data, 
    {'external': external_widget, 'final_forecast_df': fixed(final_forecast_df)}
)
# Display a markdown heading
display(hbox)
display(interactive_output)
display(output)

HBox(children=(Dropdown(description='external:', options=('Ext # 3601 - FAR-1082 Bird Refuge', 'Ext # 3602 - S…

Output()

Output()

# Export data for shiny app

In [9]:
# export data for shiny app


# Define transformer from UTM Zone 12N (EPSG:32612) to WGS84 Lat/Lon (EPSG:4326)
transformer = pyproj.Transformer.from_crs("EPSG:32612", "EPSG:4326", always_xy=True)

# Apply transformation to create 'lon' and 'lat' columns
external_xy_df['lon'], external_xy_df['lat'] = transformer.transform(
    external_xy_df['x_utm12n'].values,
    external_xy_df['y_utm12n'].values
)

aadt_df.drop(columns=['external','segid','name']).dropna().astype(int).to_csv('externals-app/data/historic.csv', index=False)
previous_forecasts_df.drop(columns=['external','forecast','name']).rename(columns={'AADT':'previous_forecast'}).sort_values(by=['externalid','year']).astype(int).to_csv('externals-app/data/forecasts-previous.csv', index=False)
external_xy_df.to_csv('externals-app/data/externals.csv', index=False)
final_forecast_df.drop(columns=['external','name','linear_forecast_notes','segid','PROJ_GRP']).fillna(0).astype(int).to_csv('externals-app/data/forecasts.csv', index=False)
linear_forecast_selected_df[linear_forecast_selected_df['linear_forecast']>0].drop(columns=['PROJ_GRP','linear_forecast_notes','segid','name','external']).fillna(0).astype(int).to_csv('externals-app/data/linear-forecasts.csv', index=False)

In [10]:
final_forecast_df

,externalid,PROJ_GRP,linear_forecast_notes,segid,year,linear_forecast,name,external,manual_adj,final_forecast
0,3601,Since 2003,as early as there is data,1082_000.0,2027,890,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge,NaN,900
1,3601,Since 2003,as early as there is data,1082_000.0,2032,989,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge,NaN,1000
2,3601,Since 2003,as early as there is data,1082_000.0,2036,1069,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge,NaN,1100
3,3601,Since 2003,as early as there is data,1082_000.0,2046,1268,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge,NaN,1300
4,3601,Since 2003,as early as there is data,1082_000.0,2055,1447,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge,NaN,1400
...,...,...,...,...,...,...,...,...,...,...
172,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2032,4248,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms,NaN,4200
173,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2036,4588,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms,NaN,4600
174,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2046,5437,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms,NaN,5400
175,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2055,6202,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms,NaN,6200
176,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2060,6627,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms,NaN,6600