In [37]:
import ipywidgets as widgets
from IPython.display import display
import pandas as pd
import plotly.express as px

In [38]:
# load data from previous notebooks
aadt_df = pd.read_csv('intermediate/external-historic-aadt.csv')
linear_forecast_df = pd.read_csv('results/linear-forecasts.csv')
externals_df = pd.read_csv('params/externals.csv')
previous_forecasts_df = pd.read_csv('intermediate/previous-forecasts.csv')
external_xy_df = pd.read_csv('data/external-x-y.csv')

Create interactive chart with assist from ChatGPT: https://chat.openai.com/share/496c1584-22b6-4c72-9815-395e11718907

In [39]:
previous_forecasts_df

     externalid  year     AADT forecast
0          3601  2020    750.0     v900
1          3602  2020   9570.0     v900
2          3603  2020   1480.0     v900
3          3604  2020  28390.0     v900
4          3605  2020   3840.0     v900
..          ...   ...      ...      ...
140        3625  2060    200.0     v900
141        3626  2060   5250.0     v900
142        3627  2060    450.0     v900
143        3628  2060  54260.0     v900
144        3629  2060   3660.0     v900

[145 rows x 4 columns]

In [40]:
# MAKE INTERACTIVE CHART

# Create a lookup dictionary
name_lookup = externals_df.set_index('externalid')['name'].to_dict()

# Map names to the forecast df
linear_forecast_df['name'] = linear_forecast_df['externalid'].map(name_lookup)

# Build the final string
linear_forecast_df['external'] = (
    'Ext # ' +
    linear_forecast_df['externalid'].fillna(0).astype(int).astype(str) +
    ' - ' +
    linear_forecast_df['name'].fillna('')
)

# Map names to the forecast df
previous_forecasts_df['name'] = previous_forecasts_df['externalid'].map(name_lookup)

# Build the final string
previous_forecasts_df['external'] = (
    'Ext # ' +
    previous_forecasts_df['externalid'].fillna(0).astype(int).astype(str) +
    ' - ' +
    previous_forecasts_df['name'].fillna('')
)
previous_forecasts_df = previous_forecasts_df[previous_forecasts_df['year'] > 2023]

# Map names to the forecast df
aadt_df['name'] = aadt_df['externalid'].map(name_lookup)

# Build the final string
aadt_df['external'] = (
    'Ext # ' +
    aadt_df['externalid'].fillna(0).astype(int).astype(str) +
    ' - ' +
    aadt_df['name'].fillna('')
)

# Create a dropdown widget for external selection
external_widget = widgets.Dropdown(
    options=previous_forecasts_df['external'].unique().tolist(),
    description='external:',
    disabled=False
)

projgrp_widget = widgets.SelectMultiple(
    options=sorted(linear_forecast_df['PROJ_GRP'].dropna().unique()),
    description='Proj Groups:',
    disabled=False
)

# Display function
def plot_data(external, projgrp):

    output.clear_output()
    global firstTime
   
    if firstTime:
        firstTime = False
    else:
        filteredlinear_forecast_df = linear_forecast_df[(linear_forecast_df['external'] == external) & (linear_forecast_df['PROJ_GRP'].isin(projgrp))]
        filteredaadt_df = aadt_df[(aadt_df['external'] == external)]
        filteredprevious_forecast_df = previous_forecasts_df[(previous_forecasts_df['external'] == external)]
        fig = px.line(filteredlinear_forecast_df, x='year', y='LIN_FORECAST', color='PROJ_GRP',
                    title=f'Linear Forecast for {external}',
                    labels={'LIN_FORECAST': 'AADT', 'year': 'Year'},
                    markers=True) 
        fig.update_traces(line=dict(dash='dash'))
        fig.update_traces(marker=dict(size=20))
    
        # Adding the scatter plot from dfHistoricAADT
        fig.add_scatter(x=filteredaadt_df['year'], y=filteredaadt_df['AADT'], mode='markers', 
                        marker=dict(size=10, color='darkgrey', symbol='circle'), name='Historic AADT')
        
        fig.update_layout(height=500, width=1000)
        fig.update_xaxes(range=[1980, 2060+2])

        max_LinF = linear_forecast_df[(linear_forecast_df['external'] == external)]['LIN_FORECAST'].max()
        max_Aadt = filteredaadt_df['AADT'].max()
        overall_max = max(max_LinF, max_Aadt)
        fig.update_yaxes(range=[0,overall_max+1000])
    
        # Adding the scatter plot from dfHistoricAADT
        fig.add_scatter(x=filteredprevious_forecast_df['year'], y=filteredprevious_forecast_df['AADT'], mode='markers', 
                        marker=dict(size=10, color='orange', symbol='circle'), name='v9.0 Forecast')
                                    
        fig.show()
        
# to keep VS CODE from duplicating chart images use global firstTime
firstTime = True

# create output widget to display filtered DataFrame
output = widgets.Output()
vbox = widgets.VBox([external_widget, projgrp_widget])

# create interactive widget
interactive_output = widgets.interactive_output(plot_data, {'external': external_widget, 'projgrp': projgrp_widget})
hbox2 = widgets.HBox([vbox, interactive_output])

# Display a markdown heading
display(hbox2)
#display(interactive_output)
display(output)

HBox(children=(VBox(children=(Dropdown(description='external:', options=('Ext # 3601 - FAR-1082 Bird Refuge', …

Output()

In [41]:
selected_forecast_df = pd.DataFrame([
    [3601, 'Since 2003', 'as early as there is data'                                                                                    ],
    [3602, 'Since 1981', 'as early as there is data, and trying not to get too high when using 2002 or higher'                          ],
    [3603, 'Since 2016', 'trying to split difference between forecast using earlier data and forecast using 2020+ data'                 ],
    [3604, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3605, 'Since 2002', 'earlier data jumps areound too much'                                                                          ],
    [3606, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3607, 'Since 2007', 'data does not look consistent till 2007'                                                                      ],
    [3608, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3609, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3610, 'No Data'   , ''                                                                                                             ],
    [3611, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3612, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3613, 'Since 2009', 'pre 2009 data is much higher than post 2009 data'                                                             ],
    [3614, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3615, 'Since 2007', 'erratic data. 2007 tries to split difference between 2004-2012 data and 2013-2023 data'                       ],
    [3616, 'Since 2006', 'data pretty consistent since 2006'                                                                            ],
    [3617, 'Since 2011', 'data pretty consistent since 2011'                                                                            ],
    [3618, 'Since 2007', 'data pretty consistent since 2007, but forecast from 1981 is much higher than 2007-2023 data'                 ],
    [3619, 'No Data'   , ''                                                                                                             ],
    [3620, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time'                                           ],
    [3621, 'No Data'   , ''                                                                                                             ],
    [3622, 'No Data'   , ''                                                                                                             ],
    [3623, 'Since 1981', 'as early as there is data, trend looks pretty consistent over time. outlier in 1983 does not change the trend'],
    [3624, 'Since 1990', 'data pretty consistent since 2017, but puts forecast too high'                                                ],
    [3625, 'No Data'   , ''                                                                                                             ],
    [3626, 'Since 1981', 'as early as there is data, despite some variation early on, trend looks pretty consistent over time'          ],
    [3627, 'No Data'   , ''                                                                                                             ],
    [3628, 'Since 1984', 'as early as there is data, trend looks pretty consistent over time except for past two years, keep eye on it' ],
    [3629, 'Since 2011', 'data pretty consistent since 2011'                                                                            ]
], columns=['externalid','PROJ_GRP', 'linear_forecast_notes'])

linear_forecast_selected_df = pd.merge(selected_forecast_df, linear_forecast_df, on=['externalid','PROJ_GRP'])
linear_forecast_selected_df

,externalid,PROJ_GRP,linear_forecast_notes,segid,year,LIN_FORECAST,name,external
0,3601,Since 2003,as early as there is data,1082_000.0,2003,412,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
1,3601,Since 2003,as early as there is data,1082_000.0,2027,890,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
2,3601,Since 2003,as early as there is data,1082_000.0,2032,989,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
3,3601,Since 2003,as early as there is data,1082_000.0,2036,1069,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
4,3601,Since 2003,as early as there is data,1082_000.0,2046,1268,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
...,...,...,...,...,...,...,...,...
198,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2032,4248,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
199,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2036,4588,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
200,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2046,5437,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
201,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2055,6202,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
202,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2060,6627,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms

In [61]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import ipywidgets as widgets
from IPython.display import display, clear_output

# Create a dropdown widget for external selection
external_widget = widgets.Dropdown(
    options=previous_forecasts_df['external'].unique().tolist(),
    description='external:',
    disabled=False
)

output = widgets.Output()
firstTime = True

def plot_data(external, manual_adj_df):
    output.clear_output()
    global firstTime

    if firstTime:
        firstTime = False
    else:
        # Filter datasets by selected external
        filteredlinear_forecast_selected_df = linear_forecast_selected_df[(linear_forecast_selected_df['external'] == external)]
        filteredaadt_df = aadt_df[(aadt_df['external'] == external)]
        filteredprevious_forecast_df = previous_forecasts_df[(previous_forecasts_df['external'] == external)]

        # Merge manual adjustments into the forecast dataframe
        merged_df = pd.merge(
            filteredlinear_forecast_selected_df,
            manual_adj_df,
            left_on=['externalid', 'year'],
            right_on=['externalid', 'year'],
            how='left'
        )
        merged_df = merged_df[merged_df['year']>=2023]

        # Create 'Final Forecast' column: manual_adj overrides LIN_FORECAST
        merged_df['Final Forecast'] = merged_df.apply(
            lambda row: row['LIN_FORECAST'] + row['manual_adj'] if pd.notnull(row['manual_adj']) else row['LIN_FORECAST'],
            axis=1
        )

        # === 🛠️ ROUND Final Forecast based on value ranges
        def custom_round(x):
            if x < 100:
                return round(x / 10) * 10
            elif x < 1000:
                return round(x / 50) * 50
            elif x < 10000:
                return round(x / 100) * 100
            elif x < 100000:
                return round(x / 500) * 500
            else:
                return round(x / 1000) * 1000

        merged_df['Final Forecast'] = merged_df['Final Forecast'].apply(custom_round)
        # === 🛠️ END ROUNDING

        # === Create base figure with linear forecast
        fig = px.line(
            filteredlinear_forecast_selected_df,
            x='year',
            y='LIN_FORECAST',
            title=f'Forecast for {external}',
            labels={'LIN_FORECAST': 'AADT', 'year': 'Year'},
        )

        # === Style the linear forecast trace
        fig.update_traces(line=dict(color='lightblue'), mode='lines+markers')
        fig.update_traces(marker=dict(size=20, color='lightblue', symbol='circle'))
        fig.update_traces(name="Linear Extrapolation", showlegend=True)

        # === Add Historic AADT as a new scatter trace
        historic_trace = go.Scatter(
            x=filteredaadt_df['year'],
            y=filteredaadt_df['AADT'],
            mode='markers',
            marker=dict(size=10, color='darkgrey', symbol='circle'),
            name='Historic AADT'
        )
        fig.add_trace(historic_trace)

        # === Reorder traces so 'Historic AADT' appears first in the legend
        fig.data = (fig.data[-1],) + fig.data[:-1]  # Moves last-added (historic) trace to the front
        
        # Add Final Forecast overlay
        fig.add_scatter(
            x=merged_df['year'], y=merged_df['Final Forecast'], mode='markers',
            marker=dict(size=15, color='red'),
            name='RTP 2027 Forecast'
        )

        # Add v9.0 Forecast
        fig.add_scatter(
            x=filteredprevious_forecast_df['year'], y=filteredprevious_forecast_df['AADT'], mode='markers',
            marker=dict(size=10, color='orange', symbol='circle'), name='RTP 2023 Forecast'
        )

        # Update axis ranges to accommodate all values
        max_LinF = filteredlinear_forecast_selected_df['LIN_FORECAST'].max()
        max_Aadt = filteredaadt_df['AADT'].max()
        max_manual = manual_adj_df['manual_adj'].max() if not manual_adj_df.empty else 0
        max_final = merged_df['Final Forecast'].max()
        #overall_max = max(max_LinF, max_Aadt, max_manual, max_final)

        fig.update_yaxes(range=[0,None])
        fig.update_xaxes(range=[1980, 2062])
        fig.update_layout(height=500)

        fig.show()

In [63]:
# to keep VS CODE from duplicating chart images use global firstTime
firstTime = True

from ipywidgets import interactive_output, fixed

# create output widget to display filtered DataFrame
output = widgets.Output()
hbox = widgets.HBox([external_widget])


# Example manual adjustment data
manual_adj_df = pd.DataFrame([
    [3602, 2027,   500],
    [3602, 2032,   300],
    [3602, 2036,   200],
    [3602, 2046,   100],
    [3605, 2027,   100],
    [3608, 2027,   100],
    [3610, 2027,   100],
    [3610, 2027,   100],
    [3610, 2027,   100],
    [3612, 2027,  4000],
    [3612, 2032,  2000],
    [3612, 2036,  1000],
    [3613, 2027,    50],
    [3613, 2032,     0],
    [3613, 2036,     0],
    [3613, 2046,     0],
    [3613, 2055,     0],
    [3615, 2027,   300],
    [3615, 2032,   300],
    [3615, 2036,   200],
    [3620, 2027,   500],
    [3623, 2027,   500],
    [3623, 2032,   500],
    [3623, 2036,   500],
    [3626, 2027,   300],
    [3626, 2032,   200],
    [3626, 2036,   100],
    [3628, 2027, 10000],
    [3628, 2032,  8000],
    [3628, 2036,  6000],
    [3628, 2046,  3000],
    [3610, 2027,   100],
    [3610, 2032,   100],
    [3610, 2036,   100],
    [3610, 2046,   150],
    [3610, 2055,   150],
    [3610, 2060,   200],
    [3619, 2027,   450],
    [3619, 2032,   450],
    [3619, 2036,   500],
    [3619, 2046,   550],
    [3619, 2055,   550],
    [3619, 2060,   600],
    [3621, 2027,   350],
    [3621, 2032,   350],
    [3621, 2036,   400],
    [3621, 2046,   400],
    [3621, 2055,   450],
    [3621, 2060,   450],
    [3622, 2027,   150],
    [3622, 2032,   150],
    [3622, 2036,   150],
    [3622, 2046,   200],
    [3622, 2055,   200],
    [3622, 2060,   200],
    [3624, 2027,   600],
    [3624, 2032,   500],
    [3624, 2036,   400],
    [3624, 2046,   200],
    [3624, 2055,   100],
    [3624, 2060,     0],
    [3625, 2027,   150],
    [3625, 2032,   150],
    [3625, 2036,   150],
    [3625, 2046,   200],
    [3625, 2055,   200],
    [3625, 2060,   200],
    [3627, 2027,   350],
    [3627, 2032,   350],
    [3627, 2036,   400],
    [3627, 2046,   400],
    [3627, 2055,   450],
    [3627, 2060,   450]
], columns=['externalid','year','manual_adj'])


# Use `fixed()` for manual_adj_df
interactive_output = widgets.interactive_output(
    plot_data, 
    {'external': external_widget, 'manual_adj_df': fixed(manual_adj_df)}
)
# Display a markdown heading
display(hbox)
display(interactive_output)
display(output)

HBox(children=(Dropdown(description='external:', index=12, options=('Ext # 3601 - FAR-1082 Bird Refuge', 'Ext …

Output()

Output()

In [44]:
# Example manual adjustment data
manual_adj_df = pd.DataFrame([
    [3602, 2027, 4000],
], columns=['externalid','year','manual_adj'])

# Create a dropdown widget for external selection
external_widget = widgets.Dropdown(
    options=linear_forecast_selected_df['external'].unique().tolist(),
    description='external:',
    disabled=False
)

external = "Ext # 3602 - SR-13/83 to Corinne"

filteredlinear_forecast_selected_df = linear_forecast_selected_df[(linear_forecast_selected_df['external'] == external)]
filteredaadt_df = aadt_df[(aadt_df['external'] == external)]
filteredprevious_forecast_df = previous_forecasts_df[(previous_forecasts_df['external'] == external)]

# Merge manual adjustments into the forecast dataframe
merged_df = pd.merge(
    filteredlinear_forecast_selected_df,
    manual_adj_df,
    left_on  = ['externalid', 'year'],
    right_on = ['externalid', 'year'],
    how = 'left'
)
display(linear_forecast_selected_df)
display(merged_df)

,externalid,PROJ_GRP,linear_forecast_notes,segid,year,LIN_FORECAST,name,external
0,3601,Since 2003,as early as there is data,1082_000.0,2003,412,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
1,3601,Since 2003,as early as there is data,1082_000.0,2027,890,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
2,3601,Since 2003,as early as there is data,1082_000.0,2032,989,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
3,3601,Since 2003,as early as there is data,1082_000.0,2036,1069,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
4,3601,Since 2003,as early as there is data,1082_000.0,2046,1268,FAR-1082 Bird Refuge,Ext # 3601 - FAR-1082 Bird Refuge
...,...,...,...,...,...,...,...,...
198,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2032,4248,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
199,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2036,4588,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
200,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2046,5437,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
201,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2055,6202,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms
202,3629,Since 2011,data pretty consistent since 2011,1826_004.9,2060,6627,FAR-1826 South Ridge Farms,Ext # 3629 - FAR-1826 South Ridge Farms

,externalid,PROJ_GRP,linear_forecast_notes,segid,year,LIN_FORECAST,name,external,manual_adj
0,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,1981,3875,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne,NaN
1,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2027,10557,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne,4000.0
2,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2032,11284,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne,NaN
3,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2036,11865,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne,NaN
4,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2046,13318,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne,NaN
5,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2055,14625,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne,NaN
6,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2060,15352,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne,NaN

In [45]:
filteredlinear_forecast_selected_df

,externalid,PROJ_GRP,linear_forecast_notes,segid,year,LIN_FORECAST,name,external
7,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,1981,3875,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne
8,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2027,10557,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne
9,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2032,11284,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne
10,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2036,11865,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne
11,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2046,13318,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne
12,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2055,14625,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne
13,3602,Since 1981,"as early as there is data, and trying not to g...",0013_006.5,2060,15352,SR-13/83 to Corinne,Ext # 3602 - SR-13/83 to Corinne